#!/bin/bash

# hamonikr-sb v 1.0.1
# Copyright (C) 2019 HamoniKR (https://hamonikr.org)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# echo "The script you are running has basename `basename "$0"`, dirname `dirname "$0"`"
# echo "The present working directory is `pwd`"

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

# Make sure only root can run 
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Run with options
case "$1" in
	create-key ) echo "Create RSA key pair for HamoniKR"
		openssl genrsa -out hamonikr.rsa 2048
		openssl req -new -x509 -sha256 -subj '/CN=HAMONIKR' -key hamonikr.rsa -out hamonikr.pem
		openssl x509 -in hamonikr.pem -inform PEM -out hamonikr.der -outform DER

		# guid=$(uuidgen)
		# //echo $guid	

		# sbsiglist --owner $guid --type x509 --output hamonikr.der.siglist hamonikr.der	

		# sudo mkdir -p /etc/secureboot/keys/{PK,KEK,db,dbx}
		# sudo cp *.PK.signed /etc/secureboot/keys/PK/
		# sudo cp *.KEK.signed /etc/secureboot/keys/KEK/
		# sudo cp *.db.signed /etc/secureboot/keys/db/	
		# for n in PK KEK db
		# do
		# 	sbvarsign --key hamonikr.rsa --cert hamonikr.pem \
		# 			--output hamonikr.der.siglist.$n.signed \
		# 				$n hamonikr.der.siglist
		# done	
		;;

	update-chain ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Apply Secure Chain for HamoniKR"
		if [ ! -d "ubuntu" ]; then
			mkdir ubuntu
		fi
		# first, ubuntu sb backup
		sudo cp /boot/efi/EFI/ubuntu/shimx64.efi ubuntu/shimx64.efi
		sudo cp /boot/efi/EFI/ubuntu/grubx64.efi ubuntu/grubx64.efi				

		if [ ! -d "output" ]; then
			mkdir output
		fi			

		sbkeysync --verbose --pk --dry-run

		# stage1 with shim
		sudo sbsign --key hamonikr.rsa --cert hamonikr.pem --output output/shimx64.efi /boot/efi/efi/ubuntu/shimx64.efi
		# sudo cp /boot/efi/EFI/ubuntu/shimx64.efi{,.bak}
		sudo cp output/shimx64.efi /boot/efi/EFI/ubuntu/
		sudo chmod 700 output/shimx64.efi /boot/efi/EFI/ubuntu/shimx64.efi
		
		# stage2 with grub
		sudo sbsign --key hamonikr.rsa --cert hamonikr.pem --output output/grubx64.efi /boot/efi/efi/ubuntu/grubx64.efi
		# sudo cp /boot/efi/EFI/ubuntu/grubx64.efi{,.bak}
		sudo cp output/grubx64.efi /boot/efi/EFI/ubuntu/
		sudo chmod 700 output/grubx64.efi /boot/efi/EFI/ubuntu/grubx64.efi		
		;;

	verify-hamonikr ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Verify Secure Chain Sigining Files for HamoniKR"	
		echo -e "${red}"	
		sudo sbverify --cert hamonikr.pem /boot/efi/efi/ubuntu/shimx64.efi     
		echo ""			
		sudo sbverify --cert hamonikr.pem /boot/efi/efi/ubuntu/grubx64.efi 
		echo -e "${green}"				
		echo -e "Current System Secure Booting State"
		echo -e "${red}"		
		sudo mokutil --sb-state
		echo "${reset}"				
		;;

	verify-ubuntu ) echo  "=============================================="
		# 검증을 위한 pem 파일 변환
		# Ubuntu key download
		# https://git.launchpad.net/qa-regression-testing/tree/notes_testing/secure-boot/keys

		# Create ubuntu pem key 
		# openssl x509 -inform DER -in ./keys/canonical-master-public.der \
		# 			-outform PEM -out ./keys/canonical-master-public.pem

		# Create MS pem key 
		openssl x509 -inform DER -in ./keys/microsoft-kekca-public.der -outform PEM -out ./keys/microsoft-kekca-public.pem
		openssl x509 -inform DER -in ./keys/microsoft-pca-public.der -outform PEM -out ./keys/microsoft-pca-public.pem
		openssl x509 -inform DER -in ./keys/microsoft-uefica-public.der -outform PEM -out ./keys/microsoft-uefica-public.pem		

		echo -e "${green}"	
		echo  "Verify Secure Chain Sigining Files for Ubuntu"	
		echo -e "${red}"	
		sudo sbverify --cert ./keys/microsoft-uefica-public.pem /boot/efi/efi/ubuntu/shimx64.efi
		
		echo ""			
		sudo sbverify --cert ./keys/canonical-master-public.pem /boot/efi/efi/ubuntu/grubx64.efi 
		echo -e "${green}"				
		echo -e "Current System Secure Booting State"
		echo -e "${red}"		
		sudo mokutil --sb-state
		echo "${reset}"				
		;;

	verify ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Verify Secure Chain for HamoniKR"
		echo  ""	
		echo  "Check HamoniKR Sign"		
		$0 verify-hamonikr
		echo  ""	
		echo  "Check Ubuntu Sign"				
		$0 verify-ubuntu		
		;;		
	install ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Install Secure Chain for HamoniKR"
		$0 update-chain
		$0 verify

		# copy secure chain public key for HamoniKR
		sudo cp hamonikr.der /boot/efi/EFI/hamonikr.der
		echo -e "${red}"
		echo -e "[CAUTION]YOU CAN'T USE SECUTE BOOT Before SETTING in BIOS"		
		echo -e "[CAUTION]CHANGE Secure SETTING in BIOS with /EFI/hamonikr.der KEY"
		echo "${reset}"				
		;;		

	restore ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Restore Original Ubuntu Secure Chain"
		# restore for stage1
		if [ -e "ubuntu/shimx64.efi" ] ; then
			sudo cp ubuntu/shimx64.efi /boot/efi/EFI/ubuntu/shimx64.efi
		else
			echo -e "${red}"			
			echo "FILE NOT FOUND : ubuntu/shimx64.efi"
			echo "${reset}"					
			exit 1			
		fi
		
		# restore for stage2
		if [ -e "ubuntu/grubx64.efi" ] ; then
			sudo cp ubuntu/grubx64.efi /boot/efi/EFI/ubuntu/grubx64.efi
		else
			echo -e "${red}"			
			echo "FILE NOT FOUND : ubuntu/grubx64.efi"
			echo "${reset}"					
			exit 1
		fi		

		if [ -e "/boot/efi/EFI/hamonikr.der" ] ; then
			sudo rm -f /boot/efi/EFI/hamonikr.der		
		else
			echo -e "${red}"			
			echo "FILE NOT FOUND : /boot/efi/EFI/hamonikr.der"
			echo "${reset}"					
			exit 1
		fi	

		echo -e "${green}"	
		echo -e "Finished Restore to Original Ubuntu Secure Chain."		
		$0 verify		
		echo "${reset}"			
		;;						
	backup ) echo  "=============================================="
		echo -e "${green}"	
		echo  "Backup Original Image to ./ubuntu folder"
		if [ ! -d "ubuntu" ]; then
			mkdir ubuntu
		fi
		# first, ubuntu sb backup
		sudo cp /boot/efi/EFI/ubuntu/shimx64.efi ubuntu/shimx64.efi
		sudo cp /boot/efi/EFI/ubuntu/grubx64.efi ubuntu/grubx64.efi
		ls -al ubuntu/
		$0 verify
		;;		
	*) 
		echo "Secure Chainning Program for HamoniKR v 1.0"	
		echo "=========================================================="	
		echo "Usage : $0 install | restore | verify"
		echo ""	
		echo "sudo $0 install : Apply Secure Chain for HamoniKR"		
		echo "sudo $0 restore : Restore Original Ubuntu Secure Chain"
		echo "sudo $0 verify : Verify Secure Chain Sigining Files for HamoniKR"			
		exit
	;;
esac